apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-dep
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: mdb
  template:
    metadata:
      labels:
        app: mdb
    spec:
      volumes:
       - name: pv
         persistentVolumeClaim:
            claimName: {{ .Values.name }}-pvc
      containers:
       - name: mongo
         image: {{ .Values.image }}
         volumeMounts:
           - name: pv
             mountPath: "/data/db"
